ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "appointmentReason" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "department" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "preferredDate" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "preferredTime" TEXT;
